### ISSUE TITLE
Share the Font Layer selected by the slider on mobile

### ISSUE THREAD

**Issue by ponceta** [camptocamp/GeoMapFish#45]
### Who requested this new feature?
Ville de Pully

### Is your feature request related to a problem?
Yes,
When sharing this on mobile : https://map.cartoriviera.ch/s/0RGql

![image](https://user-images.githubusercontent.com/8614223/108333913-b4c75d00-71d1-11eb-8ce8-1a079a318994.png)

Results on this :

![image](https://user-images.githubusercontent.com/8614223/108334297-138cd680-71d2-11eb-81de-b8a44181acc8.png)

Instead of this :

![image](https://user-images.githubusercontent.com/8614223/108334351-21425c00-71d2-11eb-9de8-cb5594b33459.png)

### Describe the solution you'd like

A more what you see is what you get approach when sharing.

### Additional information or points to watch out for
Bug on GMF 2.3, 2.4, 2.5

**Comment by rbovard** [comment]
I think it was fixed with https://github.com/camptocamp/ngeo/pull/6770

Can you reproduce it on https://geomapfish-demo-2-5.camptocamp.com/ ?

**Comment by ponceta** [comment]
There's not font layer slider on https://geomapfish-demo-2-5.camptocamp.com/ so not possible to reproduce.

Not fixed at least on 2.5.109. 

This requires maybe to add the font layer slider functionnality implemented on mobile?

**Comment by rbovard** [comment]
Indeed, I hadn't understood it like that.

But I'm not sure it's very mobile friendly to have a slider for background layers...
